modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="lanternofthewoodlands"
version="4.1.0"
displayName="Lantern of The Woodlands"
displayURL="https://legacy.curseforge.com/members/tannyjung/projects"
logoFile="logo.png"
credits="Created with MCreator"
authors="TannyJung"
description="MAGIC!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.lanternofthewoodlands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration