modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="lotw"
version="1.1.4"
displayName="Lantern of The Woodlands"
credits="Created with MCreator"
displayURL="https://www.curseforge.com/members/tannyjung/projects"
logoFile="logo.png"
authors="TannyJung"
description='''
A magic lantern with nature magic spells
'''

[[dependencies.lotw]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




