modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="lantern_of_the_woodlands"
version="1.0.0"
displayName="Lantern of the Woodlands"
credits="Created using MCreator"
displayURL="https://www.curseforge.com/members/tannyjung/projects"
logoFile="logo.png"
authors="TannyJung"
description='''
An magical lantern with nature spells
'''

[[dependencies.lantern_of_the_woodlands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




