modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="tanscomplexmagic"
version="1.0.0"
displayName="Tan's Complex Magic"
displayURL="https://legacy.curseforge.com/members/tannyjung/projects"
logoFile="logo.png"
credits="Created with MCreator"
authors="TannyJung"
description="MAGIC!"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.tanscomplexmagic]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tanscomplexmagic]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration